# Generated by Django 2.0.13 on 2019-12-25 03:02

from Django.conf import settings
import Django.core.validators
from Django.db import migrations, models
import Django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=11, validators=[Django.core.validators.RegexValidator('^010[1-9]\\d{7}$')])),
                ('user', models.ForeignKey(on_delete=Django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
