# Generated by django 2.0.13 on 2019-12-27 07:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_comment_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server', models.CharField(max_length=10)),
                ('username', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator])),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='user_agent',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='gameuser',
            unique_together={('server', 'username')},
        ),
    ]
